name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! Thanks for your first issue, we will answer it ASAP :)"
        pr-message: "Hi! Thanks for your first PR! We will look at it ASAP :)"
